# Generated by Django 2.2.2 on 2019-09-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20190806_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y%m%d', verbose_name='フォト'),
        ),
    ]
