# Generated by Django 2.2.2 on 2020-01-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y%m%d', verbose_name='フォト'),
        ),
    ]
